"""
Prompt templates for Chase the Source.
"""

from .templates import (
    ATTRIBUTION_ASSEMBLY_SYSTEM,
    ATTRIBUTION_ASSEMBLY_USER,
    CLAIM_EXTRACTION_SYSTEM,
    CLAIM_EXTRACTION_USER,
    EVIDENCE_RELEVANCE_SYSTEM,
    EVIDENCE_RELEVANCE_USER,
    SOURCE_ATTRIBUTION_SYSTEM,
    SOURCE_ATTRIBUTION_USER,
    SOURCE_CLASSIFICATION_SYSTEM,
    SOURCE_CLASSIFICATION_USER,
)

__all__ = [
    "ATTRIBUTION_ASSEMBLY_SYSTEM",
    "ATTRIBUTION_ASSEMBLY_USER",
    "CLAIM_EXTRACTION_SYSTEM",
    "CLAIM_EXTRACTION_USER",
    "EVIDENCE_RELEVANCE_SYSTEM",
    "EVIDENCE_RELEVANCE_USER",
    "SOURCE_ATTRIBUTION_SYSTEM",
    "SOURCE_ATTRIBUTION_USER",
    "SOURCE_CLASSIFICATION_SYSTEM",
    "SOURCE_CLASSIFICATION_USER",
]
